version: '3.4'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  userhistory:
    image: 1111199999katekilgyan/userhistory:userhistory
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTS=-Dspring.datasource.url=jdbc:postgresql://database:5432/postgres
      -Dspring.datasource.username=admin
      -Dspring.datasource.password=password
      -Dserver.port=8080"
